require("allan.plugins-setup")
require("allan.core.autocommands")
require("allan.core.options")
require("allan.core.keymaps")
require("allan.core.colorscheme")
-- require("allan.plugins.vim-maximizer")
require("allan.plugins.comment")
require("allan.plugins.nvim-tree")
require("allan.plugins.lualine")
require("allan.plugins.telescope")
require("allan.plugins.nvim-cmp")
require("allan.plugins.lsp.mason")
require("allan.plugins.lsp.lspconfig")
require("allan.plugins.lsp.lspsaga")
require("allan.plugins.nvim-treesitter")
require("allan.plugins.autopairs")
require("allan.plugins.gitsigns")
require("allan.plugins.fugitive")
require("allan.plugins.toggleterm")
-- require("allan.plugins.bufferline")
require("allan.plugins.null-ls")
